 diff -q calc_rates_dust_C13.c  ~/grackle/src/clib/calc_rates_dust_C13.c
 diff -q calc_rates_dust_C20.c  ~/grackle/src/clib/calc_rates_dust_C20.c
 diff -q calc_rates_dust_C25.c  ~/grackle/src/clib/calc_rates_dust_C25.c
 diff -q calc_rates_dust_C30.c  ~/grackle/src/clib/calc_rates_dust_C30.c
 diff -q calc_rates_dust_F13.c  ~/grackle/src/clib/calc_rates_dust_F13.c
 diff -q calc_rates_dust_F15.c  ~/grackle/src/clib/calc_rates_dust_F15.c
 diff -q calc_rates_dust_F50.c  ~/grackle/src/clib/calc_rates_dust_F50.c
 diff -q calc_rates_dust_F80.c  ~/grackle/src/clib/calc_rates_dust_F80.c
 diff -q calc_rates_dust_P170.c ~/grackle/src/clib/calc_rates_dust_P170.c
 diff -q calc_rates_dust_P200.c ~/grackle/src/clib/calc_rates_dust_P200.c
 diff -q calc_rates_dust_Y19.c  ~/grackle/src/clib/calc_rates_dust_Y19.c
 diff -q calc_rates_dust_loc.c  ~/grackle/src/clib/calc_rates_dust_loc.c
