version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  jobs:
    install:
      - python -m pip install --upgrade pip
      - pip install --group 'docs'

sphinx:
  # Path to your Sphinx configuration file.
  configuration: doc/source/conf.py
