version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    install:
      - pwd
      - pip --version
      - pip install --group 'docs'

sphinx:
  # Path to your Sphinx configuration file.
  configuration: doc/source/conf.py
