#! /bin/bash

echo "Issue the following commands:"
GRACKLE_DIR=`pwd`
echo "export DYLD_LIBRARY_PATH=\$DYLD_LIBRARY_PATH:${GRACKLE_DIR}/clib"
echo "export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:${GRACKLE_DIR}/clib"
echo "export PYTHONPATH=\$PYTHONPATH:${GRACKLE_DIR}/python"
